add parallel execution
Hirrus-dev/otus-go-hw pull request #5
Opened 2024-06-04 15:58 UTC by Hirrus-dev

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-06-06 07:04 UTC, dshemin requested changes

2024-06-06 07:04 UTC, dshemin commented on hw05_parallel_execution/run.go
> +		for i := 0; i < len(tasks); i++ {
Важно:

```
for _, task := range tasks  {
    // ...
}
```

2024-06-06 07:04 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	maxErrCount := 0
Критично:

Данная переменна не защищена от конкурентного доступа. Можете обратить внимание на ошибку в пайплайне:

```
Write at 0x00c0000a6da8 by goroutine 20:
  github.com/Hirrus-dev/otus-go-hw/hw05_parallel_execution.Run.func3()
      /home/runner/work/otus-go-hw/otus-go-hw/hw05_parallel_execution/run.go:61 +0x76

Previous read at 0x00c0000a6da8 by goroutine 9:
  github.com/Hirrus-dev/otus-go-hw/hw05_parallel_execution.Run.func1()
      /home/runner/work/otus-go-hw/otus-go-hw/hw05_parallel_execution/run.go:31 +0xbe
```

Мы меняем эту переменую на строке 61 и, в это же время, читаем на строке 31.

Тут надо применить мютекс или атомик. Атомик предпочтительней.

2024-06-06 07:04 UTC, dshemin commented on hw05_parallel_execution/run.go
> +			time.Sleep(time.Millisecond)
Важно:

Для чего тут эта задержка?

2024-06-06 07:04 UTC, dshemin commented on hw05_parallel_execution/run.go
> +		for {
Важно:

Можно просто:
```
for result := range resultsChannel {
    // ...
}
```

2024-06-06 17:26 UTC, Hirrus-dev commented
С первыми тремя замечаниями разобрался

2024-06-08 02:53 UTC, dshemin approved these changes

2024-06-11 12:32 UTC, merged